title: Diva Awanisa Nahdi # your name (or website title) here
logo: "/images/foto-circle.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>Final Year Engineering Management Student at Institut Teknologi Bandung</b>
  <br><br>
  An undergraduate student with passion and experiences in both educational and professional field in data analytics and strategic management
  <br><br>
  <a href="https://www.linkedin.com/in/diva-awanisa-nahdi-742336192/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
