title: Diva Awanisa Nahdi # your name (or website title) here
logo: "/images/foto-square.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Final year Engineering Management Undergraduate Student
  <br><br>
  Passionate in data analytics
  <br><br>
  <a href="https://www.linkedin.com/in/diva-awanisa-nahdi-742336192/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
