title: Diva Awanisa Nahdi # your name (or website title) here
logo: "/images/foto-circle-warna.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>Fresh Graduate in Engineering Management at Institut Teknologi Bandung</b>
  <br><br>
  A lifetime student with educational and professional experiences in data analytics and strategic management. This is my portofolio page for Data Analytics using Python, R, SQL, and Tableau
  <br><br>
  <a href="https://www.linkedin.com/in/diva-awanisa-nahdi-742336192/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
